### ISSUE TITLE
Deploy `node-exporter-full` Grafana dashboard

### ISSUE THREAD

**Issue by NicolasT** [scality/metal-k8s#12]
When deploying `kube-prometheus`, we should also ship the `node-exporter-full` dashboard from https://github.com/rfrail3/grafana-dashboards/blob/master/prometheus/node-exporter-full.json (see https://grafana.com/dashboards/1860)

Note: the dashboard needs to be altered slightly to work out of the box! The `job` value in the templating selector is wrong, should be `node_exporter` (or was it `node-exporter`?) instead of `node`, if I remember correctly.

**Comment by NicolasT** [comment]
So, after https://github.com/rfrail3/grafana-dashboards/pull/4 and https://github.com/rfrail3/grafana-dashboards/pull/6, it looks like no more changes are required :man_dancing: and we can use the upstream dashboard as-is. Thanks for the great dashboard @rfrail3.

**Comment by rfrail3** [comment]
You're welcome @NicolasT

**Comment by NicolasT** [comment]
https://github.com/scality/metal-k8s/pull/21
