### ISSUE TITLE
Monitor all system volumes with node_exporter

### ISSUE THREAD

**Issue by NicolasT** [scality/metal-k8s#31]
Currently `node_exporter` doesn't monitor all volumes available on the system: as https://github.com/prometheus/node_exporter/blob/1f11a86d594173ca1146ac1d1715cd6263e9959d/README.md#using-docker mentions, we'd need to bind all volumes in a `node_exporter` VM, which is impractical, most certainly because we're not setting up the `node_exporter` `DaemonSet` ourself...

It may be possible to work around this using `MountPropagation` and some other settings (but then see https://github.com/prometheus/node_exporter/pull/672 and https://github.com/prometheus/node_exporter/pull/660), which is far from ideal.

Maybe the best way forward would be to simply deploy `node_exporter` on all nodes, as it's intended to be deployed, and not let `kube-prometheus` (or `prometheus-operator`) manage it, just make sure the metrics are collected as intended.

**Comment by ballot-scality** [comment]
We might rely on https://copr.fedorainfracloud.org/coprs/ibotty/prometheus-exporters/
As stated in the node exporter README it is a 3rdparty maintained closely with upstream.

**Comment by NicolasT** [comment]
Cool. Would you want to work on this? We may need to figure out how to let `kube-prometheus` then use the host-installed exporter and such...

**Comment by NicolasT** [comment]
https://github.com/coreos/prometheus-operator/issues/569#issuecomment-380727999
